=== SrAllen14/101LMSGIProyectoLMSGI/ud4/03/03.dtd
<!ELEMENT programmingLanguajes (languaje)+>
<!ELEMENT languaje (description, example)> 
<!ELEMENT description (#PCDATA)>
<!ELEMENT example (#PCDATA)>
<!ATTLIST languaje name CDATA #REQUIRED>

=== SrAllen14/101LMSGIProyectoLMSGI/ud4/03/03.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE programmingLanguajes SYSTEM "03.dtd">
<!-- 
Nombre: Alvaro Allen
Descripcion: diferentes tipos de lenguajes.
-->
<?xml-stylesheet type="text/css" href="css/estilos.css"?>
<programmingLanguajes>
    <languaje name="Python">
        <description>
            Python es un lenguaje de programacion interpretado, de alto nivel y de propósito general.
        </description>
        <example>
            <![CDATA[ def saludo():
                 print("¡Hola, Mundo!")
            saludo()]]>
        </example>
    </languaje>
    <languaje name="JavaScript">
        <description>
            JavaScript es un lenguaje de programación que se utiliza para crear contenido dinámica en la web.
        </description>
        <example>
            <![CDATA[ function saludo(){
                alert("¡Hola, mundo!");
            }]]>
        </example>
    </languaje>
    <languaje name="Java">
        <description>
            Java es un lenguaje de programación de propósito general que es ampliamente utilizado en aplicaciones
            empresariales y móviles.
        </description>
        <example>
            <![CDATA[ public class Saludo{
                public static void main(String[] args){
                    System.out.println("¡Hola, mundo!");
                }
            }]]>
        </example>
    </languaje>
    <languaje name="C++">
        <description>
            C++ es un lenguaje de programación de propósito general, conocido por su eficiencia y eso en aplicaciones
            de alto rendimiento.
        </description>
        <example>
            <![CDATA[ 
            #include <iostream>
            using namespace std;

            int main() {
                cout << "¡Hola, Mundo!" << endl;
                return 0;
            }]]>
        </example>
    </languaje>
    <languaje name="Ruby">
        <description>
            Ruby es un lenguaje de programación dinámico y de alto nivel, conocido por su sintaxis 
            simple y elegante
        </description>
        <example>
            <![CDATA[ 
            def saludo
                puts "¡Hola, Mundo!"
            end

            saludo]]>
        </example>
    </languaje>
</programmingLanguajes>
